// Fetches remote proofs for a recent mainnet state and writes a fixture checked by a fork test.
//   BEACON_PROOF_URL=https://lodestar-mainnet.chainsafe.io node scripts/remote-probe.ts
import { writeFileSync } from "node:fs";
import { RemoteBeacon, remoteProofs } from "../src/remote.ts";
import { encodeBalanceProof, encodePendingConsolidationProof, encodeSlotProof, encodeStateRootProof, encodeValidatorProof } from "../src/abi.ts";

import { createPublicClient, http } from "viem";
import { mainnet } from "viem/chains";
const el = createPublicClient({ chain: mainnet, transport: http(process.env.MAINNET_RPC_URL) });
const node = new RemoteBeacon(process.env.BEACON_PROOF_URL ?? "https://lodestar-mainnet.chainsafe.io", el as never);
const head = await node.header("finalized");
const slot = Number(head.message.slot);
const pcs = await node.pendingConsolidations(slot);

const pc = pcs[pcs.length - 1];
const t0 = Date.now();
const p = await remoteProofs(node, head.root, { validators: [0, pc.source], balances: [0], pending: pc, slot: true });
console.log(`slot ${slot}: ${p.validators.length} validators, pending #${p.pending?.queueIndex}, ${Date.now() - t0} ms`);

// the EL block that stores this root in EIP-4788 (fork there to verify onchain)
const blocks = await el.getBlock({ blockTag: "latest" });
let blockNumber: bigint | undefined;
for (let n = blocks.number; n > blocks.number - 400n; n--) {
  const b = await el.getBlock({ blockNumber: n });
  if (Number(b.timestamp) === p.timestamp) { blockNumber = n; break; }
  if (Number(b.timestamp) < p.timestamp) break;
}
const blk = blockNumber ? { data: { message: { body: { execution_payload: { block_number: blockNumber.toString() } } } } } : undefined;
writeFileSync(
  "../contracts/test/fixtures/remote.json",
  JSON.stringify(
    {
      note: "Proofs from the Lodestar proof API (no state download). Generated by proof-generator/scripts/remote-probe.ts",
      source: node.baseUrl,
      beaconSlot: slot,
      elTimestamp: p.timestamp,
      elBlockNumber: blk ? Number(blk.data.message.body.execution_payload.block_number) : null,
      encoded: {
        stateRootProof: encodeStateRootProof(p.stateRootProof),
        slotProof: encodeSlotProof(p.slotProof!),
        validator0: encodeValidatorProof(p.validators[0]),
        pendingSource: encodeValidatorProof(p.validators[1]),
        balance0: encodeBalanceProof(p.balances[0]),
        pendingConsolidation: encodePendingConsolidationProof(p.pending!),
      },
    },
    (_, v) => (typeof v === "bigint" ? v.toString() : v),
    2,
  ),
);
console.log("wrote ../contracts/test/fixtures/remote.json");
