#!/usr/bin/env bash
# Copies contract ABIs, proof ABIs and the local deployment into the frontend.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=frontend/src/generated
mkdir -p "$OUT" frontend/public
{
  echo "// Generated by scripts/export-frontend.sh. Do not edit."
  for c in NativeStakeMarket Stake7702Delegate BeaconOracle StakePortHook StakePortSwapRouter UniswapStakePriceOracle AquaStakeBidApp; do
    printf 'export const %sAbi = ' "$(echo ${c:0:1} | tr A-Z a-z)${c:1}"
    jq -c .abi "contracts/out/$c.sol/$c.json" | tr -d '\n'
    echo " as const;"
  done
} > "$OUT/abis.ts"
cp proof-generator/src/abi.ts "$OUT/proofAbi.ts"
sed -i '' 's#^import type .*$#// proof types are decoded with viem#' "$OUT/proofAbi.ts"
sed -i '' '/^export const encode/,$d' "$OUT/proofAbi.ts"
sed -i '' '/^import { encodeAbiParameters }/d' "$OUT/proofAbi.ts"
cp deployments/${DEPLOYMENT_NAME:-local}.json frontend/public/deployment.json
echo "exported to $OUT and frontend/public/deployment.json"
