// Generates a proof fixture from a real mainnet beacon state.
//
//   node --max-old-space-size=12000 src/cli.ts [--slot <slot>] [--out <file>]
//
// The fixture contains everything needed to verify, against the EIP-4788 root of one execution
// block, the fields of a sellable source validator, a 0x02 target validator and a real pending
// consolidation.
import { writeFileSync } from "node:fs";
import { createPublicClient, http, getAddress } from "viem";
import { mainnet } from "viem/chains";
import { getExecutionPayloadInfo, getHeader, getStateSsz } from "./beacon.ts";
import {
  BeaconState,
  balanceProof,
  pendingConsolidationProof,
  slotProof,
  stateRootProof,
  validatorProof,
  type BeaconStateView,
} from "./proofs.ts";
import {
  encodeBalanceProof,
  encodePendingConsolidationProof,
  encodeSlotProof,
  encodeStateRootProof,
  encodeValidatorProof,
} from "./abi.ts";

const args = new Map<string, string>();
for (let i = 2; i < process.argv.length; i += 2) args.set(process.argv[i].replace(/^--/, ""), process.argv[i + 1]);

const el = createPublicClient({ chain: mainnet, transport: http(process.env.MAINNET_RPC_URL) });

const SLOTS_PER_EPOCH = 32;
const SHARD_COMMITTEE_PERIOD = 256;
const MIN_ACTIVATION_BALANCE = 32_000_000_000;
const MAX_EFFECTIVE_BALANCE_ELECTRA = 2_048_000_000_000;

const credPrefix = (c: Uint8Array) => c[0];
const credAddress = (c: Uint8Array) => getAddress(`0x${Buffer.from(c.subarray(12)).toString("hex")}`);

async function isEoa(addr: `0x${string}`) {
  const code = await el.getCode({ address: addr });
  return !code || code === "0x";
}

async function findValidator(
  state: BeaconStateView,
  start: number,
  pred: (i: number) => boolean,
): Promise<number> {
  const n = state.validators.length;
  for (let i = start; i < n; i++) {
    if (!pred(i)) continue;
    const addr = credAddress(state.validators.getReadonly(i).withdrawalCredentials);
    if (await isEoa(addr)) return i;
  }
  throw new Error("no matching validator");
}

async function main() {
  const slot = Number(args.get("slot") ?? (await getHeader("finalized")).message.slot);
  const header = await getHeader(slot);

  // The EL block of the next non-empty slot stores this block root in the EIP-4788 buffer.
  let payload;
  for (let s = slot + 1; s < slot + 8; s++) {
    try {
      payload = await getExecutionPayloadInfo(s);
      break;
    } catch {
      /* missed slot */
    }
  }
  if (!payload || payload.parentRoot !== header.root) throw new Error("could not find child block");

  console.log(`slot ${slot} root ${header.root} -> EL block ${payload.blockNumber} ts ${payload.timestamp}`);
  const state = BeaconState.deserializeToView(await getStateSsz(slot));
  const currentEpoch = Math.floor(state.slot / SLOTS_PER_EPOCH);

  const isActiveNotExiting = (i: number) => {
    const v = state.validators.getReadonly(i);
    return (
      !v.slashed &&
      v.activationEpoch + SHARD_COMMITTEE_PERIOD <= currentEpoch &&
      v.exitEpoch === Infinity
    );
  };

  const sellable = await findValidator(state, Number(args.get("sourceStart") ?? 1_000_000), (i) => {
    const v = state.validators.getReadonly(i);
    return isActiveNotExiting(i) && credPrefix(v.withdrawalCredentials) === 1 && v.effectiveBalance === MIN_ACTIVATION_BALANCE;
  });
  const target = await findValidator(state, Number(args.get("targetStart") ?? 0), (i) => {
    const v = state.validators.getReadonly(i);
    return (
      isActiveNotExiting(i) &&
      credPrefix(v.withdrawalCredentials) === 2 &&
      v.effectiveBalance + MIN_ACTIVATION_BALANCE <= MAX_EFFECTIVE_BALANCE_ELECTRA
    );
  });
  const pcIndex = state.pendingConsolidations.length - 1;
  const pc = state.pendingConsolidations.getReadonly(pcIndex);

  const srp = stateRootProof(header.message, payload.timestamp);
  const validators = [sellable, target, pc.sourceIndex, pc.targetIndex].map((i) => validatorProof(state, i));
  const balances = [sellable, target].map((i) => balanceProof(state, i));
  const pcp = pendingConsolidationProof(state, pcIndex);
  const sp = slotProof(state);

  const json = {
    note: "Real Ethereum mainnet beacon data. Generated by proof-generator/src/cli.ts",
    beaconSlot: slot,
    beaconBlockRoot: header.root,
    elBlockNumber: payload.blockNumber,
    elTimestamp: payload.timestamp,
    stateRoot: srp.stateRoot,
    roles: {
      sellableSource: sellable,
      target,
      pendingSource: pc.sourceIndex,
      pendingTarget: pc.targetIndex,
      pendingQueueIndex: pcIndex,
    },
    withdrawalAddresses: {
      sellableSource: credAddress(state.validators.getReadonly(sellable).withdrawalCredentials),
      target: credAddress(state.validators.getReadonly(target).withdrawalCredentials),
      pendingSource: credAddress(state.validators.getReadonly(pc.sourceIndex).withdrawalCredentials),
    },
    encoded: {
      stateRootProof: encodeStateRootProof(srp),
      slotProof: encodeSlotProof(sp),
      pendingConsolidationProof: encodePendingConsolidationProof(pcp),
      validatorProofs: {
        sellableSource: encodeValidatorProof(validators[0]),
        target: encodeValidatorProof(validators[1]),
        pendingSource: encodeValidatorProof(validators[2]),
        pendingTarget: encodeValidatorProof(validators[3]),
      },
      balanceProofs: {
        sellableSource: encodeBalanceProof(balances[0]),
        target: encodeBalanceProof(balances[1]),
      },
    },
  };
  const out = args.get("out") ?? `../contracts/test/fixtures/mainnet-${slot}.json`;
  writeFileSync(out, JSON.stringify(json, (_, v) => (typeof v === "bigint" ? v.toString() : v), 2));
  console.log(`wrote ${out}`, json.roles);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
