// Builds a replay fixture of a REAL mainnet consolidation for checkpoint 1.
//
//   node --max-old-space-size=14000 src/replay.ts --block <el block with the request> --tx <tx hash>
//
// The fork starts one block before the request. StakePort fills the same (source, target) pair with
// proofs from the pre-request beacon state, then proves checkpoint 1 with the REAL beacon state right
// after the request block. That root is real, but it is later than the fork block, so the demo writes
// it into the fork's EIP-4788 buffer at the timestamp mainnet stored it under.
import { readFileSync, writeFileSync } from "node:fs";
import { createPublicClient, getAddress, http, type Hex } from "viem";
import { mainnet } from "viem/chains";
import { getStateSsz } from "./beacon.ts";
import { BeaconState, pendingConsolidationProof, stateRootProof, validatorProof } from "./proofs.ts";
import { encodePendingConsolidationProof, encodeStateRootProof, encodeValidatorProof } from "./abi.ts";

const args = new Map<string, string>();
for (let i = 2; i < process.argv.length; i += 2) args.set(process.argv[i].replace(/^--/, ""), process.argv[i + 1]);
const block = BigInt(args.get("block")!);
const txHash = args.get("tx") as Hex;
const GENESIS = 1606824023;
const PREDEPLOY = "0x0000BBdDc7CE488642fb579F8B00f3a590007251";

const el = createPublicClient({ chain: mainnet, transport: http(process.env.MAINNET_RPC_URL) });
const data = new URL("../data/", import.meta.url).pathname;
const header = (slot: number) => JSON.parse(readFileSync(`${data}header-${slot}.json`, "utf8")).data;

async function main() {
  const [b, next] = await Promise.all([el.getBlock({ blockNumber: block }), el.getBlock({ blockNumber: block + 1n })]);
  const slot = (Number(b.timestamp) - GENESIS) / 12;
  const preSlot = slot - 2; // root stored by 4788 in block - 1
  const postSlot = slot; // post-state of the block that carried the request
  const pre = header(preSlot);
  const post = header(postSlot);
  // the fork block (block - 1) stores the pre-state block root in EIP-4788
  if ((await el.getBlock({ blockNumber: block - 1n })).parentBeaconBlockRoot !== pre.root) {
    throw new Error("pre root is not stored by the fork block");
  }
  if (next.parentBeaconBlockRoot !== post.root) throw new Error("post root is not stored by block + 1");

  // requests in the tx: source_address(20) || source_pubkey(48) || target_pubkey(48)
  const receipt = await el.getTransactionReceipt({ hash: txHash });
  const requests = receipt.logs
    .filter((l) => l.address.toLowerCase() === PREDEPLOY.toLowerCase())
    .map((l) => ({ address: getAddress(`0x${l.data.slice(2, 42)}`), source: `0x${l.data.slice(42, 138)}`, target: `0x${l.data.slice(138, 234)}` }))
    .filter((r) => r.source !== r.target);
  console.log(`${requests.length} consolidation requests in ${txHash}`);

  console.log("loading pre and post states…");
  const preState = BeaconState.deserializeToView(await getStateSsz(preSlot));
  const postState = BeaconState.deserializeToView(await getStateSsz(postSlot));
  const epoch = Math.floor(preSlot / 32);

  const pubkeyIndex = new Map<string, number>();
  const wanted = new Set(requests.flatMap((r) => [r.source, r.target]));
  const vals = preState.validators.getAllReadonlyValues();
  vals.forEach((v, i) => {
    const k = `0x${Buffer.from(v.pubkey).toString("hex")}`;
    if (wanted.has(k)) pubkeyIndex.set(k, i);
  });

  const pendings = postState.pendingConsolidations.getAllReadonlyValues();
  for (const r of requests) {
    const s = pubkeyIndex.get(r.source);
    const t = pubkeyIndex.get(r.target);
    if (s === undefined || t === undefined) continue;
    const sv = vals[s];
    const tv = vals[t];
    const ok =
      (sv.withdrawalCredentials[0] === 1 || sv.withdrawalCredentials[0] === 2) &&
      !sv.slashed && sv.exitEpoch === Infinity && sv.activationEpoch + 256 <= epoch &&
      tv.withdrawalCredentials[0] === 2 && !tv.slashed && tv.exitEpoch === Infinity && tv.activationEpoch <= epoch &&
      tv.effectiveBalance + sv.effectiveBalance <= 2048e9;
    const j = pendings.findLastIndex((p) => p.sourceIndex === s && p.targetIndex === t);
    if (!ok || j < 0) continue;

    const fixture = {
      note: "Replay of a real mainnet consolidation. Generated by proof-generator/src/replay.ts",
      requestTx: txHash,
      requestBlock: Number(block),
      forkBlock: Number(block) - 1,
      fillTimestamp: Number(b.timestamp),
      seller: r.address,
      sellerIsContract: ((await el.getCode({ address: r.address })) ?? "0x") !== "0x",
      buyer: getAddress(`0x${Buffer.from(tv.withdrawalCredentials.subarray(12)).toString("hex")}`),
      sourceIndex: s,
      targetIndex: t,
      pre: { slot: preSlot, root: pre.root },
      post: { slot: postSlot, root: post.root, timestamp: Number(next.timestamp), pendingIndex: j },
      encoded: {
        fill: {
          stateRootProof: encodeStateRootProof(stateRootProof(pre.header.message, Number(b.timestamp) - 12)),
          source: encodeValidatorProof(validatorProof(preState, s)),
          target: encodeValidatorProof(validatorProof(preState, t)),
        },
        accepted: {
          stateRootProof: encodeStateRootProof(stateRootProof(post.header.message, Number(next.timestamp))),
          pendingConsolidationProof: encodePendingConsolidationProof(pendingConsolidationProof(postState, j)),
          sourceProof: encodeValidatorProof(validatorProof(postState, s)),
        },
      },
    };
    const out = args.get("out") ?? "../contracts/test/fixtures/replay.json";
    writeFileSync(out, JSON.stringify(fixture, null, 2));
    console.log(`wrote ${out}: source ${s} -> target ${t}, pending index ${j}`);
    return;
  }
  throw new Error("no request satisfies the market's fill conditions");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
